### PR TITLE
v1.3 sensitivity files

### PR DESCRIPTION
**Pull request by ariedel**
Saving the v1.3 sensitivity output files for later comparisons

### CODE REVIEW

**Comment by vglaidler** [comment]
Can you please add to the readme that the directory layout includes data files corresponding to each JWST ETC public release; a description of the npz contents, and a pointer to a draft document that describes the larger process by which these files are created, vetted, used, and deployed?

If there is no metadata/pedigree in the npz files, should we add some?
I'm particularly interested in tracking a) the revision of the data used, and b) the revision of the tools used.

**Comment by ariedel** [comment]
There is as far as I know no metadata, and I'll need to get it from Klaus for the older versions.

**Comment by vglaidler** [comment]
@ariedel please update with the issue you raised in the meeting & tag Klaus into the conversation so we can get this moving.

**Comment by ariedel** [comment]
Quick update - I am still attempting to determine why my generated files for NIRSpec Fixed Slit do not agree with Klaus's versions. I don't think this needs to hold back the merge of this new data, though... I will add his v1.3 files and merge this.

**Comment by ariedel** [comment]
I think this is ready to merge.

**Pull request merged**
