### PR TITLE
JETC-758: Cosmic Ray changes

### PR DESCRIPTION
**Pull request by ariedel**
These are the modified sensitivity tests for the cosmic rays, where number of groups (or, in NIRCam, readout pattern time) has been halved and integrations has been doubled.

### CODE REVIEW

**Comment by ariedel** [comment]
These are plots of the new group and integration values that @bholler is referring to above, where I've halved the number of groups and doubled the number of integrations (except for NIRCam, where I changed the readout pattern from DEEP8 to MEDIUM2, and doubled) the number of integrations).
Compare these to the ones on Data PR [#458](https://github.com/spacetelescope/pandeia_data/pull/458)

MIRI:
miri_1 5_1 5_cosmicray2_lim_fluxes
miri_1 5_1 5_cosmicray2_sat_limits

NIRCam:
nircam_1 5_1 5_cosmicray2_lim_fluxes
nircam_1 5_1 5_cosmicray2_sat_limits

NIRISS:
niriss_1 5_1 5_cosmicray2_lim_fluxes
niriss_1 5_1 5_cosmicray2_sat_limits

NIRSpec:
nirspec_1 5_1 5_cosmicray2_lim_fluxes
nirspec_1 5_1 5_cosmicray2_sat_limits

**Comment by pontoppi** [comment]
Hi Adric

Thanks, I’ve looked at this in a bit more detail, and I think there a multiple issues. It all boils down to having to re-optimize the detector setup along multiple axes taking into account when we are in the readnoise limit versus the background limit. I think we’d have to make a more detailed revision of the exposure setups taking this into account. A number of observations:

- Medium8 is always better than Medium2 for SNR. That will buy you back some.
- The MIRI integrations were already quite short, so that’s indeed why we are hurt by cutting them in half, greatly increasing the readnoise. In most cases, these might be left untouched. I would say that we may even optimize a bit by making the slightly longer in some cases. That will buy us back some SNR if the goal is to keep as close as possible to the previous sensitivities.
- AMI and SOSS integrations are also already short.
- In one case, there is an error in the MIRI setup: The MIRI MRS uses 10 integrations, when 10 exposures is needed. This may buy back some SNR (not much, though from brief experimentation).

The bottom line is that I think it is my action to provide you with more detailed changes to the setups. This can be done after the CR change is merged, but has to be done before sensitivities are propagated to the sensitivity plot and JIST. I will go ahead and approve the CR change in the jira ticket.

cheers,

-Klaus

--
Dr. Klaus Pontoppidan
Project Scientist, James Webb Space Telescope
twitter: @pontoppi
Space Telescope Science Institute
3700 San Martin Dr.
Baltimore, MD 21218
(410) 338 4744<tel://(410)%20338%204744>



On December 18, 2019 at 12:50:36 PM, Adric Riedel (notifications@github.com<mailto:notifications@github.com>) wrote:

These are plots of the new group and integration values that @bholler<https://github.com/bholler> is referring to above, where I've halved the number of groups and doubled the number of integrations (except for NIRCam, where I changed the readout pattern from DEEP8 to MEDIUM2, and doubled) the number of integrations).
Compare these to the ones on Data PR #458<https://github.com/spacetelescope/pandeia_data/pull/458>

MIRI:
[miri_1 5_1 5_cosmicray2_lim_fluxes]<https://user-images.githubusercontent.com/2412871/71110205-d6bfec80-2194-11ea-82ca-182bd8eefbc6.png>
[miri_1 5_1 5_cosmicray2_sat_limits]<https://user-images.githubusercontent.com/2412871/71110218-daec0a00-2194-11ea-88ae-a80b110663a8.png>

NIRCam:
[nircam_1 5_1 5_cosmicray2_lim_fluxes]<https://user-images.githubusercontent.com/2412871/71110230-e2131800-2194-11ea-9ba4-c52792394461.png>
[nircam_1 5_1 5_cosmicray2_sat_limits]<https://user-images.githubusercontent.com/2412871/71110235-e3dcdb80-2194-11ea-9af8-18f5e18264f1.png>

NIRISS:
[niriss_1 5_1 5_cosmicray2_lim_fluxes]<https://user-images.githubusercontent.com/2412871/71110245-e93a2600-2194-11ea-9cd2-1a2e06e04965.png>
[niriss_1 5_1 5_cosmicray2_sat_limits]<https://user-images.githubusercontent.com/2412871/71110248-ec351680-2194-11ea-8ac6-8b0cab4ad703.png>

NIRSpec:
[nirspec_1 5_1 5_cosmicray2_lim_fluxes]<https://user-images.githubusercontent.com/2412871/71110262-f1926100-2194-11ea-8632-9a23287b1fe3.png>
[nirspec_1 5_1 5_cosmicray2_sat_limits]<https://user-images.githubusercontent.com/2412871/71110270-f35c2480-2194-11ea-8362-da2e06d8a8d1.png>

**Comment by vglaidler** [comment]
>The bottom line is that I think it is my action to provide you with more detailed changes to the setups. This can be done after the CR change is merged, but has to be done before sensitivities are propagated to the sensitivity plot and JIST. I will go ahead and approve the CR change in the jira ticket.

Tagging @york-stsci so he is in the loop for picking up the changes as soon as they are approved.

@pontoppi , fyi, our plan is for @york-stsci to pick up the pandeia release candidate as soon as it's ready to start regenerating the grid - that way he can do that work while we are doing the webserver release prep, and we can manage a closely coordinated release. 

I expect we will have a release candidate by about 10 Jan: will you be able to provide the necessary updates in time for them to be tested by that date? Thanks.

Marking this PR blocked til Klaus can provide the updated setup.

**Comment by vglaidler** [comment]
@bholler please weigh in on whether we should *actually* do this, in consultation with @pontoppi

**Comment by bholler** [comment]
My first reaction is that it doesn't seem right to change how the sensitivities are calculated because that almost means you can get any sensitivity you want, so the values is meaningless. From a more practical point of view, if we leave the calculation unchanged, the changes to the cosmic ray parameters will result in noticeably different sensitivities. I would prefer to reduce the stir this would cause among the user community.

Also, if the changes to the cosmic ray parameters dictates a change to the suggested maximum integration length, then it only makes sense to change the integration length for the sensitivities as well. We should definitely keep the number of times we change the detector parameters to a minimum, though. (I'm guessing this was determined to be a large task?)

cc @pontoppi @ariedel @vglaidler

**Comment by ariedel** [comment]
Closing this - the desire for continuity (as @bholler noted) will probably always outweigh the idea of a better setup for the instrument given the "new" (1.5.1) cosmic ray values.

**Pull request closed without merging**
