### PR TITLE
JETC-877: Sensitivity plots need wider grid

### PR DESCRIPTION
**Pull request by ariedel**
The sensitivity plots generated by pandeia-verification are not and probably have not been giving accurate sensitivity limits.
(see a better illustration of the issue in the comments starting here: https://github.com/spacetelescope/pandeia-verification/pull/20#issuecomment-577889960)

The culprit is the grid search - in order to find the limiting flux (SNR=10 in 10,000s) and saturation limit (saturation at ngroups=2) it generates a grid of fluxes around a starting value. Right now, from that preset IDT value it generates a grid from value/10 to value*10. If the limiting flux is above or below that limit, the system does not extrapolate but sticks to that upper or lower limit. When both the old and new runs being compared are stuck at a limit, the comparison plots have a discontinuity and the apparent change is 0.

This PR contains two things:
1. New backgrounds at the minzodi position on the benchmark date, for JWST and WFIRST, to replace the existing files - this incorporates the new thermal backgrounds for JWST, and new more accurate coordinates for both.
2. Enlarged the grid spacing ~(and in some cases altered idt_fluxes)~ so that the grid fully covers the range of limiting fluxes.

A demonstration:
Before:
nircam_1 6current_outputs_lim_fluxes

After (updated 20200121):
nircam_1 6_current_1 5 1_rc2_lim_fluxes

### CODE REVIEW

**Comment by ariedel** [comment]
Actually, WFGrism F444W looks like it needs further tweaks

**Comment by vglaidler** [comment]
Do I understand correctly that:

- the "preset idt limit" is "the starting [flux] value", which is represented in the code by a variable named idt_flux
- this PR proposes to change some of those values

If I understand correctly, and if the variable named "idt_flux" was so named because it was a value provided or specified by the IDT early on, then I think it is a _very_ bad idea to change the value of that variable without also changing the name of the variable.

If indeed some of these values should be changed, I propose that we first do a minor refactoring (likely in a separate PR that should be merged first) that:
 - renames the variable to starting_flux or something else meaningful
 - adds some metadata to these files (in the same format we use in the data files) so we can track the reasons that we change this starting value, and identify the source of the new values. (Perhaps @pontoppi can provide additional metadata like author/data/litref for these IDT values.)

Thoughts?

**Comment by vglaidler** [comment]
I don't know if @york-stsci runs this code, or just consumes the output of what we run; but I figured we should tag him into the conversation as well.

**Comment by york-stsci** [comment]
Strictly JIST uses the sensitivity numpy archives, and so it doesn't need to run the code, but if I'm creating a new grid, and the version of pandeia_verification that's available to clone doesn't have files available made with the version of pandeia that I'm using, then I just run it myself to generate those files. So I'm happy to run it, but even happier if there's no need to do so.

**Comment by ariedel** [comment]
@laidler

> the "preset idt limit" is "the starting [flux] value", which is represented in the code by a variable named idt_flux

idt_flux is the ballpark values that should be close to the limiting flux. I asked Klaus about this once, and he said IDT stood for Instrument Development Team, so I see the implications of that name and pedigree. As used, they're a central value - a grid of (usually) ten points is set up spanning idt_flux/10 to idt_flux*10 and the actual limiting flux is interpolated from there.

> this PR proposes to change some of those values
Yes. There are a few cases, like MIRI LRS Slit, where they're off from the actual limiting flux by a factor of 10, resulting in the limiting fluxes being off the grid (and therefore pinned to the maximum of the grid). For the most part, though, I've fixed the problem by increasing the width of the grid 10x (or, for some modes like NIRCam WFGrism with an enormous amount of dynamic range, 100x)

> If indeed some of these values should be changed, I propose that we first do a minor refactoring (likely in a separate PR that should be merged first) that:
> * renames the variable to starting_flux or something else meaningful
> * adds some metadata to these files (in the same format we use in the data files) so we can track the reasons that we change this starting value, and identify the source of the new values. (Perhaps @pontoppi can provide additional metadata like author/data/litref for these IDT values.)

I'm on board with this.

@york-stsci 
Whether you run this code, or you use the values I generate, the limiting fluxes produced are going to be very different after this PR. The saturations do not seem to change very much, fortunately.

**Comment by york-stsci** [comment]
@ariedel thank you for the heads up. At least at the moment, JIST pretty much only uses the saturation fluxes (and it uses them to artificially set the SNR to zero for any grid point that's above the saturation flux (which we know isn't accurate, but the JIST viewpoint is that, if you're working with even partially-saturated data, you should be working with the JETC, and not at one remove from an interpolated grid of a flat-spectrum source)). So it seems like that won't affect our high-flux limits much, so mostly it'll be a question of just running the grid once there's a version of the JETC to work from.

**Comment by ariedel** [comment]
Here's a comparison of the 1.5 plot available online (http://www.stsci.edu/jwst/science-planning/proposal-planning-toolbox/sensitivity-and-saturation-limits) to one I generated with my revised grid. The biggest difference is MIRI LRS Slit - the limiting flux trends sharply upwards in the new plot, but not the old one.
1 5comparison

I think the rest of the changes are because of the different grid spacings - I only increased the number of points IN the grid for NIRCam WF Grism, and that led to it not apparently changing all that much.

**Comment by ariedel** [comment]
The state of this PR now is that I've changed the tests so that the ONLY change is increasing the grid width - I reverted all the changes to IDT fluxes.

I also added new code to calc_limits to print warnings (which my run-all.sh script now sends to a log directory) if the limiting flux hits any of the limits.

**Comment by ariedel** [comment]
Same comparison, saturation limits.
1 5comparison_sat
The only change I can see is the MIRI F2550W filter has a higher saturation limit

**Comment by ariedel** [comment]
Here are 1.5 to 1.5.1rc2 comparisons with master, and then with this branch. I'll show both sat_limits and lim_fluxes, but for the most part the sat_limits are less interesting.

**Comment by ariedel** [comment]
MIRI:
miri_1 5_1 5 1rc2_lim_fluxes


miri_1 5_1 5 1rc2_sat_limits

**Comment by ariedel** [comment]
NIRCam:
nircam_1 5_1 5 1rc2_lim_fluxes
nircam_1 5_new_1 5 1rc2_sat_limits

**Comment by ariedel** [comment]
NIRISS:
niriss_1 5_1 5 1rc2_lim_fluxes
niriss_1 5_1 5 1rc2_sat_limits

**Comment by ariedel** [comment]
NIRSpec:
nirspec_1 5_1 5 1rc2_lim_fluxes
nirspec_1 5_1 5 1rc2_sat_limits
(the more jagged ones are the old grid)

**Comment by ariedel** [comment]
WFIRST Imager:
wfirstimager_1 5_1 5 1rc2_lim_fluxes
wfirstimager_1 5_1 5 1rc2_sat_limits
(the bump in the Prism data is only with the old grid)

**Comment by ariedel** [comment]
Merging this... @york-stsci , you should now be able to get the 1.5.1rc2 saturation limits from the files that will merge in this PR, which have been generated with the newest thermal model.

**Pull request merged**
